
services: docker

# We want all PRs built but only merges on master branch and tags under semantic version scheme
branches:
  only:
  - main
  - /^(0|[1-9]\d*)\.(0|[1-9]\d*)\.(0|[1-9]\d*)$/

jobs:
  include:
    - stage: Build and Test on OpenJDK11
      name: Build and Test on OpenJDK11
      language: java
      jdk:
        - openjdk11
      install:
        - mvn install -q -Dmaven.test.skip -Dmaven.javadoc.skip -B -V
      script:
        - mvn -Pfluency deploy -B -Dfester.s3.bucket="${AWS_BUCKET}" -Dfester.s3.access_key="${AWS_ACCESS_KEY_ID}" -Dfester.s3.secret_key="${AWS_SECRET_ACCESS_KEY}" -Ddocker.registry.username="${DOCKER_USERNAME}" -Ddocker.registry.password="${DOCKER_PASSWORD}" -Ddocker.registry.account="${DOCKER_REGISTRY_ACCOUNT}" -Dorg.slf4j.simpleLogger.log.net.sourceforge.pmd=error -DlogLevel="${PROD_LOG_LEVEL}"
      cache:
        directories:
        - $HOME/.m2

notifications:
  email:
    recipients:
      - ksclarke@ksclarke.io
    on_success: change
    on_failure: change
