#!/bin/sh

# Prevent pushes that would cause the CI build to fail.

mvn clean install

if [ $? -ne 0 ]
then
    echo >&2 "\nThe build command 'mvn clean install' failed, not pushing"
    exit 1
fi

exit 0
