openapi: "3.0.0"
tags:
  - name: Fester Operations
x-tagGroups:
  - name: Implemented
    tags:
      - Manifest
      - Collection
      - Utility
  - name: Proposed
    tags:
      - Collection (Proposed)

info:
  version: ${project.version}
  title: Fester API
  description: "Fester, a IIIF manifest storage microservice, provides a simple storage and retrieval system
    for IIIF manifests. Amazon S3 is required. For more details on how to construct a IIIF manifest, consult these
    resources: https://iiif.io/api/presentation/2.1/#manifest and https://iiif.io/api/cookbook/mvm-image/#use-case"
  license:
    name: The 3-Clause BSD License
    url: https://opensource.org/licenses/BSD-3-Clause
  contact:
    name: UCLA Library Services Team
    email: lib_softwaredev-services@library.ucla.edu
servers:
  - url: http://iiif.library.ucla.edu/fester
paths:
  /fester/status:
    get:
        tags: [Utility]
        summary: Get Application Status
        description: "This endpoint returns a JSON object with information about the status of the Fester service."
        operationId: getStatus
        responses:
          '200':
            description: A JSON object with status information
            content:
              application/json:
                schema:
                  type: object
          '500':
            description: There was an internal server error
            content:
              text/plain:
                schema:
                  type: string
                  example: The status request failed because the slithy toves did gyre
  /fester/endpoints:
    get:
        tags: [Utility]
        summary: Get S3 Endpoints Status
        description: "This endpoint returns a JSON object with information about the status of the S3 endpoints."
        operationId: checkEndpoints
        responses:
          '200':
            description: A JSON object with status information
            content:
              application/json:
                schema:
                  type: object
          '500':
            description: There was an internal server error
            content:
              text/plain:
                schema:
                  type: string
                  example: The status request failed because the slithy toves did gyre
  /collections:
    post:
      tags: [Collection]
      summary: Post a Collection
      description: "This endpoint accepts CSV data to use in the creation of IIIF manifests. There are a few columns
        that the uploaded CSV file is required to have: 'Project Name' (for collection rows), 'Title' (for work rows),
        'Item ARK', 'Parent ARK', 'Item Sequence', 'Object Type', and 'IIIF Access URL'. These are used to create the
        structure of the manifest. The location of the resulting collection manifest is returned in the 'Location'
        response header."
      operationId: postCSV
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                iiif-host:
                  type: string
                csv-file:
                  type: string
                  format: binary
      responses:
        '201':
          description: An HTML page with a link to the created manifest
          headers:
            Location:
              schema:
                type: string
                example: 'http://iiif.library.ucla.edu/collections/123456'
          content:
            text/html:
              schema:
                type: string
                format: binary
        '400':
          description: Bad request (e.g., missing or invalid CSV file)
          content:
            text/html:
              schema:
                type: string
                format: binary
        '415':
          description: Unsupported media type (i.e. not a CSV file)
          content:
            text/html:
              schema:
                type: string
                format: binary
        '500':
          description: There was an internal server error
          content:
            text/html:
              schema:
                type: string
                format: binary
  /collections/{collectionName}:
    get:
      tags: [Collection]
      summary: Get a collection
      description: Gets a specified collection.
      operationId: getCollection
      responses:
        '200':
          description: The IIIF collection for the requested ID
          content:
            application/json:
              schema:
                type: object
        '404':
          description: Not found
          content:
            text/plain:
              schema:
                type: string
                example: The collection 'FakeCollection' could not be found
        '500':
          description: Internal server error
          content:
            text/plain:
              schema:
                type: string
                example: "Internal server error: the slithy toves did gyre and gimble"
    put:
      tags: [Collection]
      summary: Put a collection
      description: Puts a provided IIIF collection.
      operationId: putCollection
      requestBody:
        description: A IIIF collection
        required: true
        content:
          application/json:
            schema:
              type: object
      responses:
        '200':
          description: Updated or created the collection with the supplied name
          content:
            text/plain:
              schema:
                type: string
                example: The collection 'MyCollection' was successfully uploaded
        '400':
          description: Bad request
          content:
            text/plain:
              schema:
                type: string
                example: "Bad request while putting collection: MyCollection"
        '403':
          description: Forbidden
          content:
            text/plain:
              schema:
                type: string
                example: "You do not have permission to put collection: MyCollection"
        '415':
          description: Unsupported media type (i.e. not JSON)
          content:
            text/plain:
              schema:
                type: string
                example: Collection 'MyCollection' does not have a valid media type
        '500':
          description: Internal server error
          content:
            text/plain:
              schema:
                type: string
                example: "Internal server error: the slithy toves did gyre and gimble"
    delete:
      tags: [Collection (Proposed)]
      summary: Delete a collection
      description: Deletes a specified collection.
      operationId: deleteCollection
      responses:
        '204':
          description: Deleted the collection with the supplied name
          content:
            text/plain:
              schema:
                type: string
                example: "Collection successfully deleted: MyCollection"
        '403':
          description: Forbidden
          content:
            text/plain:
              schema:
                type: string
                example: Permission to delete collection 'MyCollection' denied
        '500':
          description: Internal server error
          content:
            text/plain:
              schema:
                type: string
                example: "Internal server error: the slithy toves did gyre and gimble"
    parameters:
       - in: path
         name: collectionName
         required: true
         schema:
           type: string
         description: The collection name
  /{manifestId}/manifest:
    get:
      tags: [Manifest]
      summary: Get a manifest
      description: Gets a specified manifest from the store.
      operationId: getManifest
      responses:
        '200':
          description: The IIIF manifest for the requested ID
          content:
            application/json:
              schema:
                type: object
        '404':
          description: Not found
          content:
            text/plain:
              schema:
                type: string
                example: The manifest 'XYZ' could not be found
        '500':
          description: Internal server error
          content:
            text/plain:
              schema:
                type: string
                example: "Internal server error: the slithy toves did gyre and gimble"
    put:
      tags: [Manifest]
      summary: Put a manifest
      description: Puts a provided manifest in the store.
      operationId: putManifest
      requestBody:
        description: A IIIF manifest
        required: true
        content:
          application/json:
            schema:
              type: object
            examples:
              jsonObject:
                summary: A sample manifest
                externalValue: 'https://californica.library.ucla.edu/concern/works/2gqn2000zz-89112/manifest'
      responses:
        '200':
          description: Updated or created the manifest at the supplied ID
          content:
            text/plain:
              schema:
                type: string
                example: "Manifest successfully uploaded to server: XYZ"
        '400':
          description: Bad request
          content:
            text/plain:
              schema:
                type: string
                example: "Bad request while submitting manifest: XYZ"
        '403':
          description: Forbidden
          content:
            text/plain:
              schema:
                type: string
                example: Permission to upload manifest 'XYZ' denied
        '415':
          description: Unsupported media type (i.e. not JSON)
          content:
            text/plain:
              schema:
                type: string
                example: Manifest 'XYZ' upload failed because of unsupported media type
        '500':
          description: Internal server error
          content:
            text/plain:
              schema:
                type: string
                example: "Internal server error: the slithy toves did gyre and gimble"
    delete:
      tags: [Manifest]
      summary: Delete a manifest
      description: Delete the specified manifest.
      operationId: deleteManifest
      responses:
        '204':
          description: Deleted the manifest at the supplied ID
          content:
            text/plain:
              schema:
                type: string
                example: Manifest 'XYZ' has been successfully deleted
        '403':
          description: Forbidden
          content:
            text/plain:
              schema:
                type: string
                example: Permission to delete manifest 'XYZ' denied
        '404':
          description: Not found
          content:
            text/plain:
              schema:
                type: string
                example: The manifest 'FakeManifest' could not be found
        '500':
          description: Internal server error
          content:
            text/plain:
              schema:
                type: string
                example: "Internal server error: the slithy toves did gyre and gimble"
    parameters:
       - in: path
         name: manifestId
         required: true
         schema:
           type: string
         description: The manifest ID
         example: "ark:/21198/zz00090p17"
