openapi: "3.0.0"
tags:
  - name: manifest-store operations
info:
  version: 0.1.0
  title: Manifest Store API
  description: A IIIF manifest storage microservice
  license:
    name: The 3-Clause BSD License
    url: https://opensource.org/licenses/BSD-3-Clause
  contact:
    name: UCLA Library Services Team
    email: lib_softwaredev-services@library.ucla.edu
servers:
  - url: http://iiif.library.ucla.edu
paths:
  /ping:
    get:
        tags: [utility]
        summary: Ping
        description: Requests the application to acknowledge a simple request. Useful for testing the availability of the service.
        operationId: getPing
        responses:
          '200':
            description: OK
  # Collection operations are proposed, not yet implemented
  /collection/{collectionName}:
    get:
      tags: [collection, proposed]
      summary: Get a collection
      description: Gets a specified collection.
      operationId: getCollection
      responses:
        '200':
          description: The IIIF collection for the requested ID
        '404':
          description: Not found
    put:
      tags: [collection, proposed]
      summary: Put a collection
      description: Puts a provided IIIF collection.
      operationId: putCollection
      requestBody:
        description: A IIIF collection
        required: true
        content:
          application/json:
            schema:
              type: object
      responses:
        '200':
          description: Updated or created the collection with the supplied name
        '400':
          description: Bad request
        '403':
          description: Forbidden
        '415':
          description: Unsupported media type (i.e. not JSON)
        '500':
          description: Internal server error
    delete:
      tags: [collection, proposed]
      summary: Delete a collection
      description: Deletes a specified collection.
      operationId: deleteCollection
      responses:
        '204':
          description: Deleted the collection with the supplied name
        '403':
          description: Forbidden
        '500':
          description: Internal server error
    parameters:
       - in: path
         name: collectionName
         required: true
         schema:
           type: string
         description: The collection name
  /{manifestId}/manifest:
    get:
      tags: [manifest]
      summary: Get a manifest
      description: Gets a specified manifest from the store.
      operationId: getManifest
      responses:
        '200':
          description: The IIIF manifest for the requested ID
        '400':
          description: Bad request
        '404':
          description: Not found
    put:
      tags: [manifest]
      summary: Put a manifest
      description: Puts a provided manifest in the store.
      operationId: putManifest
      requestBody:
        description: A IIIF manifest
        required: true
        content:
          application/json:
            schema:
              type: object
      responses:
        '200':
          description: Updated or created the manifest at the supplied ID
        '400':
          description: Bad request
        '403':
          description: Forbidden
        '415':
          description: Unsupported media type (i.e. not JSON)
        '500':
          description: Internal server error
    delete:
      tags: [manifest]
      summary: Delete a manifest
      description: Delete the specified manifest.
      operationId: deleteManifest
      responses:
        '204':
          description: Deleted the manifest at the supplied ID
        '403':
          description: Forbidden
        '500':
          description: Internal server error
    parameters:
       - in: path
         name: manifestId
         required: true
         schema:
           type: string
         description: The manifest ID
