openapi: "3.0.0"
info:
  version: 1.0.0
  title: Manifest Store API
  license:
    name: The 3-Clause BSD License
servers:
  - url: http://images.library.ucla.edu/api
paths:
  /ping:
    get:
      operationId: getPing
      responses:
        '200':
          description: OK
  /manifests/{manifestId}:
    get:
      operationId: getManifest
      responses:
        '200':
          description: The IIIF manifest for the requested ID
        '400':
          description: Bad request
        '404':
          description: Not found
    post:
      operationId: postManifest
      requestBody:
        description: A IIIF manifest
        required: true
        content:
          application/json:
            schema:
              type: string
      responses:
        '201':
          description: Created a new manifest using the supplied ID
        '400':
          description: Bad request
        '403':
          description: Forbidden
        '415':
          description: Unsupported media type (i.e. not JSON)
        '500':
          description: Internal server error
    put:
      operationId: putManifest
      requestBody:
        description: A IIIF manifest
        required: true
        content:
          application/json:
            schema:
              type: string
      responses:
        '200':
          description: Updated the manifest at the supplied ID
        '201':
          description: Created the manifest at the supplied ID
        '400':
          description: Bad request
        '403':
          description: Forbidden
        '415':
          description: Unsupported media type (i.e. not JSON)
        '500':
          description: Internal server error
    delete:
      operationId: deleteManifest
      responses:
        '200':
          description: Deleted the manifest at the supplied ID
        '403':
          description: Forbidden
        '500':
          description: Internal server error
    parameters:
       - in: path
         name: manifestId
         required: true
         schema:
           type: string
         description: The manifest ID
  