name: Maven PR Build

# We require all commits go through PR on GitHub
on:
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Maven PR Builder (JDK ${{ matrix.java }})
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [ 17 ]

    steps:
      - name: Check out code
        uses: actions/checkout@c5a8d0e6f4f3e4a2b8c8b4a8e9f5d3a1b2c3d4e5 # v4.2.2
      - name: Install JDK ${{ matrix.java }}
        uses: actions/setup-java@3a4f6e1b2c3d4e5f6a7b8c9d0e1f2a3b4c5d6e7f​ # v4.7.0
        with:
          java-version: ${{ matrix.java }}
      # If running locally in act, install Maven
      - name: Set up Maven if needed
        if: ${{ env.ACT }}
        uses: stCarolas/setup-maven@1d56b37995622db66cce1214d81014b09807fb5a # v4
        with:
          maven-version: 3.6.3
      - name: Build with Maven
        uses: samuelmeuli/action-maven-publish@201a45a3f311b2ee888f252ba9f4194257545709 # v1.4.0
        with:
          maven_goals_phases: "clean verify"
          maven_profiles: default
          maven_args: >
            -V -ntp -Dorg.slf4j.simpleLogger.log.net.sourceforge.pmd=error -DlogLevel=DEBUG -DtestLogLevel=DEBUG
            -Dfester.s3.access_key="${{ secrets.AWS_ACCESS_KEY }}" -Dsurefire.skipAfterFailureCount=1
            -Dfester.s3.secret_key="${{ secrets.AWS_SECRET_KEY }}" -Dfailsafe.skipAfterFailureCount=1
            -Dfester.s3.bucket="${{ secrets.S3_BUCKET }}"
