name: Maven PR Build

# We require all commits go through PR on GitHub
on:
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Maven PR Builder (JDK ${{ matrix.java }})
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [ 21 ]

    steps:
      - name: Check out code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Install JDK ${{ matrix.java }}
        uses: actions/setup-java@3a4f6e1af504cf6a31855fa899c6aa5355ba6c12 # v4.7.0
        with:
          cache: maven
          distribution: 'temurin'
          java-version: ${{ matrix.java }}
          server-id: github
          server-username: ${{ secrets.JPV3_GH_USERNAME }}
          server-password: ${{ secrets.JPV3_GH_PAT }}

      # If running locally in act, install Maven
      - name: Set up Maven if needed
        if: ${{ env.ACT }}
        uses: stCarolas/setup-maven@1d56b37995622db66cce1214d81014b09807fb5a # v4
        with:
          maven-version: 3.6.3

      - name: Build with Maven
          run: >
            mvn -U -ntp clean verify
              -Dfester.s3.access_key="${{ secrets.AWS_ACCESS_KEY }}" -Dsurefire.skipAfterFailureCount=1
              -Dfester.s3.secret_key="${{ secrets.AWS_SECRET_KEY }}" -Dfailsafe.skipAfterFailureCount=1
              -Dfester.s3.bucket="${{ secrets.S3_BUCKET }}" -DlogLevel=DEBUG -DtestLogLevel=DEBUG
